apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-config
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /appdata/plex
  storageClassName: local-path
  claimRef:
    namespace: plex
    name: plex-config