apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-plex
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 32400
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      name: http
  selector:
    app: plex