apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-cert
  namespace: argocd
spec:
  secretName: argocd-server-tls
  duration: 8760h # 1 year
  renewBefore: 720h # 30 days
  dnsNames:
    - argocd.home.lab
  usages:
    - server auth
    - client auth
  issuerRef:
    name: cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io