apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: immich-cert
  namespace: immich
spec:
  secretName: immich-tls
  duration: 8760h
  renewBefore: 720h
  dnsNames:
    - immich.lab
  usages:
    - server auth
    - client auth
  issuerRef:
    name: homelab-issuer
    kind: ClusterIssuer
    group: cert-manager.io
