apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jupyterhub-cert
  namespace: jupyterhub
spec:
  secretName: jupyterhub-tls
  duration: 8760h
  renewBefore: 720h
  dnsNames:
    - jupyter.lab
  usages:
    - server auth
    - client auth
  issuerRef:
    name: homelab-issuer
    kind: ClusterIssuer
    group: cert-manager.io
