apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-cert
  namespace: monitoring
spec:
  secretName: grafana-tls
  issuerRef:
    name: homelab-issuer
    kind: ClusterIssuer
  dnsNames:
    - grafana.lab
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-cert
  namespace: monitoring
spec:
  secretName: prometheus-tls
  issuerRef:
    name: homelab-issuer
    kind: ClusterIssuer
  dnsNames:
    - prometheus.lab
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: alertmanager-cert
  namespace: monitoring
spec:
  secretName: alertmanager-tls
  issuerRef:
    name: homelab-issuer
    kind: ClusterIssuer
  dnsNames:
    - alertmanager.lab