apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: plex-cert
  namespace: plex
spec:
  secretName: plex-tls
  duration: 8760h
  renewBefore: 720h
  dnsNames:
    - plex.lab
  usages:
    - server auth
    - client auth
  issuerRef:
    name: homelab-issuer
    kind: ClusterIssuer
    group: cert-manager.io