apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: qbittorrent-cert
  namespace: qbittorrent
spec:
  secretName: qbittorrent-tls
  duration: 8760h 
  renewBefore: 720h 
  dnsNames:
    - qbittorrent.lab
  usages:
    - server auth
    - client auth
  issuerRef:
    name: homelab-issuer
    kind: ClusterIssuer
    group: cert-manager.io