apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: registry-cert
  namespace: registry
spec:
  secretName: registry-tls
  duration: 8760h
  renewBefore: 720h
  dnsNames:
    - registry.lab
  usages:
    - server auth
    - client auth
  issuerRef:
    name: homelab-issuer
    kind: ClusterIssuer
    group: cert-manager.io