apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homelab-root-cert
  namespace: cert-manager
spec:
  isCA: true
  commonName: "Homelab Root CA"
  secretName: homelab-root-cert
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: homelab-root-issuer
    kind: ClusterIssuer
    group: cert-manager.io