traefik:
  additionalArguments:
    - "--log.level=DEBUG"
    - "--providers.kubernetesingress.allowexternalnameservices=true"
    - "--providers.kubernetescrd.allowexternalnameservices=true"
    - "--serversTransport.insecureSkipVerify=true"
  ports:
    websecure:
      tls:
        enabled: true
        certResolver: ""
  service:
    type: LoadBalancer
    spec:
      loadBalancerIP: "192.168.0.10" 