traefik:
  additionalArguments:
    - "--log.level=DEBUG"
    - "--providers.kubernetesingress.allowexternalnameservices=true"
    - "--providers.kubernetescrd.allowexternalnameservices=true"
    - "--serversTransport.insecureSkipVerify=true"
  ports:
    websecure:
      tls:
        enabled: true
        certResolver: ""
  service:
    type: LoadBalancer
    spec:
      loadBalancerIP: "100.66.242.14" 
  
  providers:
    kubernetesIngress:
      ingressEndpoint:
        publishedService: "kube-system/traefik"
