# Default values for Plex
image:
  repository: lscr.io/linuxserver/plex
  tag: latest
  pullPolicy: Always

# Service configuration
service:
  type: NodePort
  port: 32400
  nodePort: 32400

# Environment configuration
environment:
  TZ: Etc/UTC
  VERSION: docker

# Storage configuration
persistence:
  config:
    path: /appdata/plex
  media:
    anime:
      path: /tank/Media/Anime
    animeFilms:
      path: /tank/Media/AnimeFilms
    homeMedia:
      path: /tank/Media/HomeMedia
    movies:
      path: /tank/Media/Movies
    music:
      path: /tank/Media/Music
    shortFilms:
      path: /tank/Media/ShortFilms
    tvSeries:
      path: /tank/Media/TVSeries
    documentaries:
      path: /tank/Media/Documentaries