apiVersion: v2
name: jupyterhub
version: 0.1.0
description: Wrapper chart to pin JupyterHub and apply homelab defaults
dependencies:
  - name: jupyterhub
    version: 4.2.0
    repository: https://jupyterhub.github.io/helm-chart