jupyterhub:
  prePuller:
    hook:
      enabled: false
    continuous:
      enabled: false
  # --- proxy & TLS ------------------------------    
  proxy:
    secretToken: "202514bc356ab5cc5897de5897c63596626a9f05e1e758e7057ce821b9cc1add"
    chp:
      networkPolicy:
        enabled: false           # homelab network is trusted
    service:                             # was publicService
      annotations:
        # If you still want this on the *Service* – otherwise move it to ingress.annotations
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
    https:
      enabled: true
  
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts: ["jupyter.lab"]
    tls:
      - hosts: ["jupyter.lab"]
        secretName: jupyterhub-tls

  hub:
    networkPolicy:
      enabled: false

  # --- single-user resources & GPU --------------
  singleuser:
    image:
      name: nvcr.io/nvidia/pytorch
      tag: 24.04-py3
    memory:
      limit: 8G
      guarantee: 4G
    cpu:
      limit: 4
      guarantee: 1
    # no "gpu:" section any more
    extraResource:
      limits:
        nvidia.com/gpu: 1          # how many you let the pod *use*
      guarantees:
        nvidia.com/gpu: 1          # how many the scheduler must *reserve*
    nodeSelector:
      nvidia.com/gpu.present: "true"
    storage:
      type: dynamic
      homeMountPath: /home/jovyan
