jupyterhub:
  prePuller:
    hook:
      enabled: false
    continuous:
      enabled: false
  # --- proxy & TLS ------------------------------    
  proxy:
    secretToken: "202514bc356ab5cc5897de5897c63596626a9f05e1e758e7057ce821b9cc1add"
    chp:
      networkPolicy:
        enabled: false           # homelab network is trusted
    service:                             # was publicService
      annotations:
        # If you still want this on the *Service* – otherwise move it to ingress.annotations
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
    https:
      enabled: true
  
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts: ["jupyter.lab"]
    tls:
      - hosts: ["jupyter.lab"]
        secretName: jupyterhub-tls

  hub:
    networkPolicy:
      enabled: false

  # --- single-user resources & GPU --------------
  singleuser:
    image:
      name: quay.io/jupyter/pytorch-notebook
      tag: cuda12-python-3.12
    memory:
      limit: 16G
      guarantee: 6G
    cpu:
      limit: 8
      guarantee: 2
    extraResource:
      limits:
        nvidia.com/gpu: 1
      guarantees:
        nvidia.com/gpu: 1
    storage:
      type: dynamic
      homeMountPath: /home/jovyan
