apiVersion: v2
name: kube-prometheus-stack
description: A Helm chart for kube-prometheus-stack
type: application
version: 0.1.0
dependencies:
  - name: kube-prometheus-stack
    version: 69.1.2
    repository: https://prometheus-community.github.io/helm-charts