apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: immich
  namespace: immich
  annotations:
    kubernetes.io/ingress.provider: traefik
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - immich.lab
      secretName: immich-tls
  rules:
    - host: immich.lab
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: immich-server
                port:
                  number: 2283
