apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-library
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tank/Media/Photos
  storageClassName: local-path
  claimRef:
    namespace: immich
    name: immich-library
