apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
data:
  lab.server: |
    lab {
        hosts {
            192.168.0.10 argocd.lab
            192.168.0.10 qbittorrent.lab
            fallthrough
        }
        forward . 8.8.8.8
        log
        errors
    }