apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
data:
  home.lab.server: |
    home.lab {
        hosts {
            192.168.0.10 argocd.lab
            # Add more entries as needed
            fallthrough
        }
        forward . 8.8.8.8
        log
        errors
    }