apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  lab.server: |
    lab {
      hosts {
        100.66.242.14 argocd.lab
        100.66.242.14 qbittorrent.lab
        100.66.242.14 grafana.lab
        100.66.242.14 prometheus.lab
        100.66.242.14 alertmanager.lab
        100.66.242.14 plex.lab
        100.66.242.14 registry.lab
        100.66.242.14 jupyter.lab
        fallthrough
      }
      forward . 8.8.8.8
      log
      errors
    }