apiVersion: v1
kind: Service
metadata:
  name: coredns-custom
spec:
  type: NodePort
  ports:
    - name: dns
      port: 53
      targetPort: 53
      protocol: UDP
      nodePort: 32053
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
      nodePort: 32053
  selector:
    k8s-app: coredns-custom