argo-cd:
  server:
    service:
      type: NodePort
      nodePortHttp: 30080
    config:
      repositories: |
        - type: git
          url: https://github.com/scrungus/homelab.git
  dex:
    enabled: false
  notifications:
    enabled: false