argo-cd:
  server:
    service:
      type: NodePort
      nodePortHttp: 30080
    config:
      repositories: |
        - type: git
          url: https://github.com/scrungus/homelab.git
      url: https://argocd.home.lab 
    certificate:
      enabled: false  # Disable ArgoCD's certificate management
    ingress:
      enabled: true
      ingressClassName: traefik
      pathType: Prefix
      hostname: argocd.home.lab
      tls: true
  dex:
    enabled: false
  notifications:
    enabled: false