argo-cd:
  server:
    service:
      type: NodePort
      nodePortHttp: 9090
      nodePortHttps: 9091
    extraArgs:
      - --insecure
    config:
      repositories: |
        - type: git
          url: https://github.com/scrungus/homelab.git
  dex:
    enabled: false
  notifications:
    enabled: false