argo-cd:
  server:
    service:
      type: NodePort
      nodePortHttp: 30080
    config:
      repositories: |
        - type: git
          url: https://github.com/scrungus/homelab.git
      url: https://argocd.home.lab 
    ingress:
      enabled: true
      hosts:
        - argocd.home.lab
      tls:
        - secretName: argocd-server-tls
          hosts:
            - argocd.home.lab
  dex:
    enabled: false
  notifications:
    enabled: false