apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-config
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /appdata/qbittorrent
  storageClassName: local-path

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-downloads
spec:
  capacity:
    storage: 500Gi  # Adjust based on your needs
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tank/torrents
  storageClassName: local-path