apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
spec:
  type: NodePort
  selector:
    app: qbittorrent
  ports:
  - name: webui
    port: 8080
    targetPort: webui
    nodePort: 30088
  - name: torrenting
    port: 6881
    targetPort: torrenting
    protocol: TCP
    nodePort: 30681